//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Joy Boy",
    "email": "joyboy@unram.ac.id",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "User delete",
    "email": "userdelete@unram.ac.id",
    "password": "123456",
    "confPassword": "123456",
    "role": "users"
}

###
//get all user
GET http://localhost:5000/users

###
//single user show
GET http://localhost:5000/users/50cd4a04-dbc5-443a-ae6f-d7f507909965

###
PATCH  http://localhost:5000/users/50cd4a04-dbc5-443a-ae6f-d7f507909965
Content-Type: application/json

{
    "name": "Joy Boy Update",
    "email": "joyboy@unram.ac.id",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

###
//delete
DELETE http://localhost:5000/users/c9ee3a34-0af3-4ac6-9b18-71b74d9c5949

###
//login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "joyboy@unram.ac.id",
    "password": "123456"
}
###
 POST http://localhost:5000/login
 Content-Type: application/json

 {
    "email": "user@unram.ac.id",
    "password": "123456"
 }
###
GET http://localhost:5000/me
###
DELETE http://localhost:5000/logout